add landing.
alexivanov89/css-practice pull request #2
Opened 2021-06-03 18:06 UTC by alexivanov89

2021-06-03 23:24 UTC, Roman-Maksimov requested changes

2021-06-03 23:24 UTC, Roman-Maksimov commented on style.css
> +    width: 1400px;
Фиксировать ширину тут не подходит, шапка должна подстраиваться под ширину окна. По сколько `div` блок, по умолчанию имеет ширину `100%`, можно вообще это свойство убрать.

2021-06-03 23:24 UTC, Roman-Maksimov commented on style.css
> +    top: 16px;
Относительное позиционирование тоже здесь не требуется. Блок имеет ширину `100%`, смещая его влево, вы делаете ширину страницы `100% + 24px`. По макету вам тут требуется отступ, а не смещение. Свойство `margin` вам поможет.

2021-06-03 23:24 UTC, Roman-Maksimov commented on style.css
> +    padding-left: 32px;
Добавьте еще верхнюю и нижнюю границы. Уж больно маленькое, по высоте, поле получилось

2021-06-03 23:24 UTC, Roman-Maksimov commented on style.css
> +    border-bottom: 2px solid #E97F03;
Вы наверняка заметили, что при фокусе на поле, происходит небольшой скачок, из-за того, что раньше границы не было, а потом она появляется толщиной в 2px. По мимо визуального дефекта это еще и приводит к так называемому reflow (пересчету остальных элементов, расположенных ниже этого инпута).
Классически такую задачу решают следующим образом:
```css
.search_input {
  ...
  border-bottom: 2px solid transparent;
  transition: border-color 0.1s ease-out;
}

.search_input:focus {
  border-color: #E97F03;
}
```

2021-06-03 23:24 UTC, Roman-Maksimov commented on style.css
> +.icon_search-active::before {
Если я правильно понял, вы предполагаете, что класс будет выставляться где-то на уровне JS. Это вполне рабочий вариант, но, по скольку мы практикуемся, хотелось бы увидеть вариант на CSS. Подсказка, можно использовать `next sibling`.

2021-06-03 23:24 UTC, Roman-Maksimov commented on style.css
> +}
Иконка уехала далековато от краев. По макету, 8px сверху, 8px справа. У вас 29 сверху и 35 справа (у вас в карточке паддинги)

2021-06-03 23:24 UTC, Roman-Maksimov commented on style.css
> +@media screen and (max-width:376px) {
376px маловато. Попробуйте разную ширину окна, в диапазоне 377px-502px на экране одна карточка в строке. Попробуйте подобрать условие так, чтобы было не меньше двух карточек в строке.

2021-06-03 23:24 UTC, Roman-Maksimov commented on style.css
> +        width: 327px;
Здесь тоже не требуется фиксировать ширину шапки

2021-06-03 23:24 UTC, Roman-Maksimov commented on style.css
> +    background-color: #E99330;
забыли тень

2021-06-03 23:24 UTC, Roman-Maksimov commented on style.css
> +}
У картинки на детальной странице есть еще рамка вокруг

2021-06-03 23:24 UTC, Roman-Maksimov commented on detailed-paige.html
> +                        <img class="image-preview" src="./img/ghome-preview.jpg" alt="ghome" />
FYI. Если экспортировать картинку в формате PNG, у неё будет прозрачный фон. JPG не умеет прозрачность.

2021-06-03 23:24 UTC, Roman-Maksimov commented on style.css
> +@media screen and (max-width:376px) {
Аналогично для детальной страницы. Подберите оптимальную ширину, чтобы не было горизонтального скрола при уменьшении окна.
PS. Не обязательно должен быть один media-запрос. Можно сделать отдельно для каталога, отдельно для детальной страницы.

2021-06-05 18:02 UTC, alexivanov89 commented
fixed

2021-06-08 11:32 UTC, Roman-Maksimov requested changes

2021-06-08 11:32 UTC, Roman-Maksimov commented on style.css
> +    }
В мобильном варианте картинка должна быть растянута на всю ширину окна (не должно быть отступов слева и справа). Так же, у картинки тут нет рамки.

2021-06-21 13:45 UTC, Roman-Maksimov approved these changes

2021-06-23 16:49 UTC, alexivanov89 commented
merge landing

2021-06-23 16:49 UTC, merged